"""calendar versions overrides templates instances

Revision ID: 3ae97b4e5200
Revises: ee93851f6cdb
Create Date: 2026-09-30 22:53:20.724189

"""
import sqlalchemy as sa

from alembic import op

revision = '3ae97b4e5200'
down_revision = 'ee93851f6cdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_versions',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('semester_id', sa.CHAR(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_versions_semester_id'), 'calendar_versions', ['semester_id'], unique=False)
    op.create_table('course_templates',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('semester_id', sa.CHAR(length=36), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('week_pattern', sa.String(length=50), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('teacher', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('textbook_id', sa.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_id', 'weekday', 'period_number', 'week_pattern', name='uq_template_slot_pattern')
    )
    op.create_index(op.f('ix_course_templates_semester_id'), 'course_templates', ['semester_id'], unique=False)
    op.create_table('schedule_instances',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('semester_id', sa.CHAR(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('teacher', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('template_id', sa.CHAR(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version_id', sa.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_id', 'date', 'period_number', name='uq_instance_slot')
    )
    op.create_index('ix_instances_semester_date', 'schedule_instances', ['semester_id', 'date'], unique=False)
    op.create_index(op.f('ix_schedule_instances_semester_id'), 'schedule_instances', ['semester_id'], unique=False)
    op.create_table('calendar_overrides',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('semester_id', sa.CHAR(length=36), nullable=False),
    sa.Column('version_id', sa.CHAR(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_type', sa.String(length=20), nullable=False),
    sa.Column('follow_weekday', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['calendar_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'date', name='uq_override_version_date')
    )
    op.create_index(op.f('ix_calendar_overrides_semester_id'), 'calendar_overrides', ['semester_id'], unique=False)
    op.create_index(op.f('ix_calendar_overrides_version_id'), 'calendar_overrides', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_overrides_version_id'), table_name='calendar_overrides')
    op.drop_index(op.f('ix_calendar_overrides_semester_id'), table_name='calendar_overrides')
    op.drop_table('calendar_overrides')
    op.drop_index(op.f('ix_schedule_instances_semester_id'), table_name='schedule_instances')
    op.drop_index('ix_instances_semester_date', table_name='schedule_instances')
    op.drop_table('schedule_instances')
    op.drop_index(op.f('ix_course_templates_semester_id'), table_name='course_templates')
    op.drop_table('course_templates')
    op.drop_index(op.f('ix_calendar_versions_semester_id'), table_name='calendar_versions')
    op.drop_table('calendar_versions')
    # ### end Alembic commands ###
