"""adjustments versions feedback constraints

Revision ID: 4230554ff809
Revises: bf501d5a9488
Create Date: 2026-10-01 00:12:19.198951

"""
from alembic import op
import sqlalchemy as sa


revision = '4230554ff809'
down_revision = 'bf501d5a9488'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraint_updates',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('source_feedback_id', sa.CHAR(length=36), nullable=True),
    sa.Column('constraint_json', sa.JSON(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constraint_updates_user_id'), 'constraint_updates', ['user_id'], unique=False)
    op.create_table('feedback_logs',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('instance_id', sa.CHAR(length=36), nullable=True),
    sa.Column('semester_id', sa.CHAR(length=36), nullable=True),
    sa.Column('feedback_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_logs_user_id'), 'feedback_logs', ['user_id'], unique=False)
    op.create_table('schedule_versions',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('semester_id', sa.CHAR(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.CHAR(length=36), nullable=False),
    sa.Column('change_summary', sa.String(length=500), nullable=False),
    sa.Column('adjustment_id', sa.CHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_versions_semester_id'), 'schedule_versions', ['semester_id'], unique=False)
    op.create_table('adjustments',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('instance_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=False),
    sa.Column('new_value', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['schedule_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjustments_instance_id'), 'adjustments', ['instance_id'], unique=False)
    op.create_index(op.f('ix_adjustments_user_id'), 'adjustments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adjustments_user_id'), table_name='adjustments')
    op.drop_index(op.f('ix_adjustments_instance_id'), table_name='adjustments')
    op.drop_table('adjustments')
    op.drop_index(op.f('ix_schedule_versions_semester_id'), table_name='schedule_versions')
    op.drop_table('schedule_versions')
    op.drop_index(op.f('ix_feedback_logs_user_id'), table_name='feedback_logs')
    op.drop_table('feedback_logs')
    op.drop_index(op.f('ix_constraint_updates_user_id'), table_name='constraint_updates')
    op.drop_table('constraint_updates')
    # ### end Alembic commands ###
