"""reminders wx subscriptions

Revision ID: 6aa5c5bc4ac8
Revises: f1cf956529dc
Create Date: 2026-10-01 01:26:26.164159

"""
from alembic import op
import sqlalchemy as sa


revision = '6aa5c5bc4ac8'
down_revision = 'f1cf956529dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('instance_id', sa.CHAR(length=36), nullable=True),
    sa.Column('reminder_type', sa.String(length=30), nullable=False),
    sa.Column('trigger_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_reminder_dedupe')
    )
    op.create_index(op.f('ix_reminders_trigger_time'), 'reminders', ['trigger_time'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_table('wx_subscriptions',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('granted_count', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wx_subscriptions_user_id'), 'wx_subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wx_subscriptions_user_id'), table_name='wx_subscriptions')
    op.drop_table('wx_subscriptions')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_trigger_time'), table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###
