"""semesters seasons bells

Revision ID: ee93851f6cdb
Revises: 21dca57675be
Create Date: 2026-09-30 22:41:02.563413

"""
from alembic import op
import sqlalchemy as sa


revision = 'ee93851f6cdb'
down_revision = '21dca57675be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semesters',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_weeks', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semesters_user_id'), 'semesters', ['user_id'], unique=False)
    op.create_table('season_periods',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('semester_id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_periods_semester_id'), 'season_periods', ['semester_id'], unique=False)
    op.create_table('bell_schedules',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('season_period_id', sa.CHAR(length=36), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_break', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['season_period_id'], ['season_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bell_schedules_season_period_id'), 'bell_schedules', ['season_period_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bell_schedules_season_period_id'), table_name='bell_schedules')
    op.drop_table('bell_schedules')
    op.drop_index(op.f('ix_season_periods_semester_id'), table_name='season_periods')
    op.drop_table('season_periods')
    op.drop_index(op.f('ix_semesters_user_id'), table_name='semesters')
    op.drop_table('semesters')
    # ### end Alembic commands ###
