"""textbooks photos instance textbook

Revision ID: f1cf956529dc
Revises: 4230554ff809
Create Date: 2026-10-01 00:30:04.591300

"""
import sqlalchemy as sa

from alembic import op

revision = 'f1cf956529dc'
down_revision = '4230554ff809'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_photos',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.Column('photo_type', sa.String(length=20), nullable=False),
    sa.Column('photo_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_photos_user_id'), 'location_photos', ['user_id'], unique=False)
    op.create_table('textbooks',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('edition', sa.String(length=50), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('cover_local_path', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.CHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.add_column('schedule_instances', sa.Column('textbook_id', sa.CHAR(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_instances', 'textbook_id')
    op.drop_table('textbooks')
    op.drop_index(op.f('ix_location_photos_user_id'), table_name='location_photos')
    op.drop_table('location_photos')
    # ### end Alembic commands ###
